# SITE CONFIGURATION
baseurl: "/"
url: "https://speedypreneur.com"
imglogo: https://postimg.cc/ftCjTv17

# THEME-SPECIFIC CONFIGURATION
title: Speedypreneur                                    # site's title
description: "Learn - Take Action - Enjoy Your Success"      # used by search engines
avatar:                          # Empty for no avatar in navbar
favicon: assets/favicon.png                             # Icon displayed in the tab

# Header and footer text
header_text: Change <code>header_text</code> in <code>_config.yml</code>  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: false
footer_text: '<p style="text-align: center;"><a href="/tos/"><span style="color: #333333;">Terms Of Service</span></a> | <span style="color: #333333;"><a style="color: #333333;" href="/privacy/">Privacy Policy</a></span> | <span style="color: #333333;"><a style="color: #333333;" href="/disclaimer/">Disclaimer</a></span> | <a href="/contact/"><span style="color: #333333;">Contact Us</span></a> | <a href="/about/"><span style="color: #333333;">About Us</span></a></p> <div class="copyright"> &copy; Copyright <strong>Speedypreneur</strong>. All Rights Reserved </div>'

# Blog
excerpt: truncate                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics: "UA-209133341-1"
cookie_consent: true                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 10
paginate_path: "/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
